# Generated by Django 3.2.20 on 2023-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
