# Generated by Django 3.2.20 on 2023-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ['-created_at'], 'verbose_name': 'scrap', 'verbose_name_plural': 'Scraps'},
        ),
        migrations.AlterField(
            model_name='qna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 일시'),
        ),
    ]
