# Generated by Django 3.2.20 on 2023-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_report_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='result',
        ),
        migrations.AddField(
            model_name='scrap',
            name='bookmarked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='causation',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='history_img',
            field=models.ImageField(default='default.png', upload_to='histories/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
