# Generated by Django 3.2.20 on 2023-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20230914_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='causation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='history_img',
            field=models.ImageField(upload_to='histories/%Y/%m/%d'),
        ),
    ]
