# Generated by Django 3.2.20 on 2023-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20230915_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='history_img',
            field=models.ImageField(upload_to='scrap/%Y/%m/%d'),
        ),
    ]
