# Generated by Django 3.2.20 on 2023-09-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_scrap_history_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='history_img',
            field=models.ImageField(upload_to='scrap/'),
        ),
    ]
