# Generated by Django 3.2.20 on 2023-09-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_history_bookmarked'),
        ('info', '0008_alter_scrap_history_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={},
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='causation',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='history_img',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='scrap',
            name='history',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='home.history'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
